version: '3.8'

services:
  # 开发环境覆盖配置
  app:
    volumes:
      - .:/var/www/html
      - ./logs:/var/log/apache2
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    ports:
      - "8080:80"
    command: >
      sh -c "php setup_database.php && apache2-foreground"

  # 开发环境不包含Nginx
  nginx:
    profiles:
      - production
